# Generated by Django 5.0.5 on 2024-05-09 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_po_pso_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='api.course'),
        ),
    ]
